name: Serializers
version: 0.1.0
description: Serializers is a Dart library for serializing objects into maps.
author: Victor Savkin <vic.savkin@gmail.com>
dependencies:
  unittest: any
  dartmocks: any